# Generated by Django 5.0 on 2026-06-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='custom_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
