# Generated by Django 5.2.15 on 2026-06-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_issue_custom_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_admin_reply',
            field=models.BooleanField(default=True),
        ),
    ]
